steps:
  - name: 'gcr.io/cloud-builders/docker'
    env: 
      - 'MESSAGE=${_MESSAGE}'
      - 'TAG=${_TAG}'
    args: ['build', '-t', 
          'asia-southeast2-docker.pkg.dev/self-trials-mgarma/flaskhello/hello:${TAG}', 
          '--build-arg', 'MESSAGE=$MESSAGE', 
          '.']

  - name: 'gcr.io/cloud-builders/docker'
    env: 
      - 'TAG=${_TAG}'
    args: ['push', 
          'asia-southeast2-docker.pkg.dev/self-trials-mgarma/flaskhello/hello:$TAG']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    env: 
      - 'TAG=${_TAG}'
    args: ['run', 'deploy', 'flask-hello', 
          '--allow-unauthenticated', 
          '--region=asia-southeast2', 
          '--image=asia-southeast2-docker.pkg.dev/self-trials-mgarma/flaskhello/hello:$TAG']
